<template>
    <div>
        <div class="container">
            <div class="privacy">
                <h2>Terms And Condition</h2>
                <h3>I. Introduction and Eligibility</h3>
                <p>Please read these Terms of Use (“Terms“) carefully before using the Service.</p>
                <p>These Terms include TRON’s Privacy Policy, which is incorporated by reference into these Terms. We have included several annotations in boxes to help explain or emphasize key sections. These annotations are for convenience only and have no legal or contractual effect.</p>
                <p>This agreement is a legally binding contract. It may change as our business changes, and you agree you will review it and any updates regularly. Your continued use of the Service means you accept any changes.</p>
                <p>Binding Agreement. These Terms constitute a binding agreement between you and PT Teknologi Rancang Olah Nusantara and its affiliates and subsidiaries (“TRON,” “Company,” “we,” “us”). “You” and “users” shall mean all users of the Service. You accept these Terms each time you access the Service. If you do not accept these Terms, you must not use the Service. If you are under 18 years of age, you represent and agree that you possess the legal consent of your parent or guardian to access and use the Service.</p>
                <p>Revisions to Terms. We may revise these Terms at any time by posting an updated version. You should visit this page periodically to review the most current Terms because you are bound by them. Your continued use of the Service after a change to these Terms constitutes your binding acceptance of these Terms.</p>
                <p>The terms “post” and “posting” as used in these Terms shall mean the act of submitting, transmitting, sharing, uploading, publishing, displaying, or similar action on the Service.</p>
                <h3>II. The Service</h3>
                <p>The “Service” means any website, mobile application, or Internet service under TRON’s control, whether partial or otherwise, in connection with providing TRON’s online platform that connects users with vehicle-sharing transportation providers in major cities. Each reservation a user makes with such vehicle-sharing transportation providers on the Service is a “Reservation,” and each ride taken through a Reservation is a “Ride.”</p>
                <p>TRON DOES NOT PROVIDE TRANSPORTATION SERVICES AND IS NOT A TRANSPORTATION CARRIER. IT IS UP TO THE THIRD-PARTY TRANSPORTATION PROVIDER, DRIVER, OR VEHICLE OPERATOR TO OFFER TRANSPORTATION SERVICES WHICH MAY BE SCHEDULED THROUGH THE SERVICE. TRON OFFERS INFORMATION AND A METHOD TO OBTAIN SUCH THIRD-PARTY TRANSPORTATION SERVICES, BUT DOES NOT AND DOES NOT INTEND TO PROVIDE TRANSPORTATION SERVICES OR ACT IN ANY WAY AS A TRANSPORTATION CARRIER, AND HAS NO RESPONSIBILITY OR LIABILITY FOR ANY TRANSPORTATION SERVICES PROVIDED TO YOU BY SUCH THIRD PARTIES.</p>
                <p>By using the Service to make a Reservation for a Ride, you are electing to use a ridesharing transportation service.</p>
                <p>The Service is currently being offered as a beta test, and as such is limited in its capacity, geographic region, and hours of operation. The geographic region and hours of operation were selected based on the Service’s limited capacity during the beta test and our anticipation of demand for the Service and have no discriminatory rationale or intention. We anticipate expanding the Service to a broader geographic area and/or additional hours of operation in the future. Should you have any recommendations for additional times and/or areas of service, please contact us at support@tron.id.</p>
                <h3>III. Eligibility to Use the Service</h3>
                <p>Children. No part of the Service is directed to persons under the age of 13. IF YOU ARE UNDER 13 YEARS OF AGE, PLEASE DO NOT USE OR ACCESS THE SERVICE AT ANY TIME OR IN ANY MANNER.</p>
                <p>No one under the age of 18 is allowed to register with or use the Service without the consent of a parent or guardian. If you are under the age of 18, by registering for and using the Service, you warrant and represent that you have consent to do so from a parent or guardian. If you are a parent or guardian of a minor who has registered for or used the Service without your consent, please contact us at support@tron.id.</p>
                <p>Agent of a Company, Entity, or Organization. If you are using the Service on behalf of a company, entity, or organization (collectively “Organization“), then you represent and warrant that you:</p>
                <p>1. are an authorized representative of that Organization</p>
                <p>2. have the authority to bind that Organization to these Terms; and</p>
                <p>3. agree to be bound by these Terms on behalf of that Organization.</p>
                <h3>IV. Your Account</h3>
                <p>You are responsible for your log-in credentials and for keeping your information accurate.</p>
                <p>You are responsible for any activity resulting from the use of your log-in credentials on the Service.</p>
                <p>You represent and warrant that the information you provide to the Company upon use of the Service and at all other times will be true, accurate, current, and complete.</p>
                <p>Your Log-In Credentials. To use the Service, you may need to log-in by providing a username, password, and cellular phone number. Your account is personal to you, and you may not share your account information with, or allow access to your account by, any third party. As you will be responsible for all activity that occurs under your access credentials (including, without limitation, the behavior of any other people that travel in your party), you agree to use reasonable efforts to prevent unauthorized access to or use of the Service and to preserve the confidentiality of your username and password, and any device that you use to access the Service.</p>
                <p>You agree to notify us immediately of any breach in secrecy of your log-in information. If you have any reason to believe that your account information has been compromised or that your account has been accessed by a third party, you agree to immediately notify the Company by e-mail to support@tron.id You will be solely responsible for the losses incurred by the Company and others due to any unauthorized use of your account.</p>
                <h3>V. Payments and Billing</h3>
                <p>TRON charges a fee (the “Fee“) for use of the Service. You will be charged when your Ride is complete, provided that we may pre-authorize and hold an estimated amount of the Fee on your card before the Ride begins. All Fees are non-refundable. Fees are exclusive of taxes and other government surcharges.</p>
                <p>Cancellation Policy. If you cancel a Reservation, we may charge you a Fee. Repeated cancellations may result in the suspension of your account, in TRON’s sole discretion.</p>
                <p>No-Show Policy. If you are not present at the time and place designated in your Reservation, we may charge you a Fee. Repeated “no-show” instances may result in the suspension of your account, in TRON’s sole discretion.</p>
                <p>Cleaning/Damage Fees. If the interior or exterior of your driver’s vehicle is damaged or dirtied as a result of intentional or negligent acts such as aggressive slamming of doors, vomiting, or pet accidents, an additional cleaning or damage Fee may be assessed and charged.</p>
                <p>TRON Credits and Promotional Codes. You may purchase credit (“TRON Credit”) towards future Rides. Purchases of TRON Credit are non-refundable and may only be used with the Service. TRON may offer promotional codes with varying features and rates that are redeemable for TRON Credit. Any such promotional code is valid until its stated expiration date.</p>
                <h3>VI. Additional Guests</h3>
                <p>If you make a Reservation and multiple people are traveling in your party, you, as the account associated with the Reservation, are responsible for the conduct of everybody traveling in your party.</p>
                <p>When you make a Reservation, you must indicate how many people are travelling in your party. If you do not, we reserve the right to refuse service to additional guests or charge an additional Fee.</p>
                <h3>VII. Communications</h3>
                <p>TRON may communicate with you by email, text message or posting notice on the Service. You may request that we provide notice of security breaches in writing.</p>
                <p>You agree to receive email from us at the email address you provided to us for customer service-related purposes.</p>
                <p>Electronic Notices. By using the Service or providing Personal Information to us, you agree that we may communicate with you electronically regarding security, privacy, and administrative issues relating to your use of the Service. If we learn of a security system’s breach, we may attempt to notify you electronically by posting a notice on the Service or sending an email to you. You may have a legal right to receive this notice in writing. To receive free written notice of a security breach (or to withdraw your consent from receiving electronic notice), please write to us at support@tron.id.</p>
                <p>SMS Text Messages. We may send you an SMS text message to the phone number you provide upon registering with the Service (i) when you register with the Service, (ii) when you make a Reservation, (iii) when your vehicle is approaching the designated pick-up location, (iv) when your vehicle is at the designated pick-up location, and (v) when you reset your password with the Service. Text message and data rates, as determined by your wireless carrier, may apply. By registering with the Service, you consent to receive these SMS text messages.</p>
                <h3>VIII. TRON’s Content Ownership and Use</h3>
                <p>TRON owns or has rights to all of the content we make available through the Service, but you may use it as you use the Service. You cannot use our logo without our written permission.</p>
                <p>The term “content” or “contents” as used generally in these Terms shall mean any text, graphics, images, music, software (excluding the Service), audio, video, information or other materials.</p>
                <p>The contents of the Service include: designs, text, graphics, images, video, information, logos, button icons, software, audio files, computer code, and other TRON content (collectively, “TRON Content“). All TRON Content and the compilation (meaning the collection, arrangement, and assembly) of all TRON Content are the property of TRON or its licensors and are protected under copyright, trademark, and other laws.</p>
                <p>License to You. We authorize you, subject to these Terms, to access and use the Service and the TRON Content solely to make Reservations. Any other use is expressly prohibited. This license is revocable at any time without notice and with or without cause. Unauthorized use of the TRON Content may violate copyright, trademark, and applicable communications regulations and statutes and is strictly prohibited. You must preserve all copyright, trademarks, service marks, and other proprietary notices contained in the original TRON Content on any copy you make of the TRON Content.</p>
                <p>TRON Marks. TRON, the TRON logo, and other TRON logos and product and service names are or may be trademarks of TRON (the “TRON Marks“). Without our prior written permission, and except as solely enabled by any link as provided by us, you agree not to display or use in any manner the TRON Marks.</p>
                <h3>IX. Intellectual Property Rights and Your License to Use</h3>
                <p>You (or the people who allow you to use their content), own all of the content you post using the Service. However, we may use it for any purpose, including in our marketing materials. We may also modify your content to make it work better.</p>
                <p>It is very important that you have permission to use other people’s content, or they (or their parent or guardian) may be able to sue you for violating their legal rights.</p>
                <p>a. TRON Claims No Ownership. The Service may provide Users with the ability to post content (“User Content“). TRON claims no ownership or control over User Content. You or a third-party licensor, as appropriate, retain all copyright, patent, and trademark rights to any of the content you post on or through the Service. You are responsible for protecting those rights.</p>
                <p>b. TRON’s Use of Posted Content on the Service. By posting User Content on or through the Service, and subject to TRON’s Privacy Policy, you grant TRON a worldwide, non-exclusive, irrevocable, perpetual, royalty-free, transferable right to license, sublicense, use, view, copy, adapt, sell, transfer, modify, remove, publish, transmit, distribute, broadcast, stream, perform or publicly display your User Content for any purpose without compensation to you, including for the purpose of promoting TRON and its services. While we will try our best to not use your User Content in a way that may be objectionable to you, you waive any rights you may have regarding your User Content being altered or manipulated in any way that may be objectionable to you. Please e-mail us at support@tron.id if you believe your User Content is being used in an objectionable manner and we will do what we reasonably can to remedy such use of your User Content. The license granted in this paragraph will continue even after you stop using the Service. TRON reserves the right to refuse to accept, post, display, or transmit any User Content at its sole discretion.</p>
                <p>c. You Acquire No Ownership in the Content of TRON or Others. You understand and agree that you will not obtain as a result of your use of the Service, any right, title or interest in or to such content delivered via the Service or in any intellectual property rights (including, without limitation, any copyrights, patents, trademarks, trade secrets or other rights) in the content. TRON alone (and its licensors, where applicable) owns all right, title and interest, including all related intellectual property rights, in and to the Service. The Company name, the Company logo, and the product names associated with the Service are trademarks of TRON or third parties, and no right or license is granted to use them.</p>
                <p>d. You Must Have Rights to the Content You Post. You represent and warrant that: (i) you own the content posted by you on or through the Service or otherwise have the right to grant the license set forth in these Terms, (ii) the posting and use of your User Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights, intellectual property rights, or any other rights of any person or entity, and (iii) the posting of User Content on the Service does not result in a breach of contract between you and a third party. You agree to pay for all royalties, fees, and any other monies owing to any person by reason of content you post on or through the Service. You also acknowledge and agree that your User Content is non-confidential and non-proprietary.</p>
                <p>e. Additional Licenses. Certain materials made available for download from or through the Service may be subject to additional or different license terms and conditions. The Service contains content from Users and other TRON licensors. Except as provided within these Terms, you may not copy, modify, translate, publish, broadcast, transmit, distribute, perform, display, or sell any content appearing on or through the Service.</p>
                <h3>X. Third-Party Content Disclaimers, Limitations, and Prohibitions</h3>
                <p>You are responsible for your actions when using and relying on the Service or content available on the Service.</p>
                <p>We do not represent or guarantee the truthfulness, accuracy, or reliability of content, posted by third parties (“Third-Party Content“). You accept that any reliance on material posted by other users or third-party service providers will be at your own risk. By using the Service you accept the risk that you might be exposed to content that is objectionable or otherwise inappropriate. TRON does not endorse any, nor is it responsible for, Third-Party Content on the Service.</p>
                <p>Do not do bad things with the Service, try to break it, or steal our hard work.<br>
                You agree to use the Service only for its intended purpose. You must use the Service in compliance with all privacy, data protection, intellectual property, and other applicable laws. The following uses of the Service are prohibited. You may not:
                </p>
                <p>1. attempt to interfere with, harm, reverse engineer, steal from, or gain unauthorized access to the Service, user accounts, or the technology and equipment supporting the Service</p>
                <p>2. frame, mirror or link to the Service without permission</p>
                <p>3. use data mining, robots, web spiders, viruses or worms or other data gathering devices on or through the Service, including any program which may make multiple server requests per second, or unduly burdens or hinders the operation or performance of the Service</p>
                <p>4. post incomplete, false, or misleading information, impersonate another person, or misrepresent your affiliation with a person or entity</p>
                <p>5. disclose personal information about another person, or post, send or store infringing, obscene, threatening, libelous or otherwise tortious material, including material that is harmful to children, violates the rights of third parties, or is intended to harass, abuse, or degrade another person</p>
                <p>6. sell, transfer, or assign any of your rights to use the Service to a third party without our express written consent</p>
                <p>7. post advertising or marketing links or content, including spam or otherwise duplicative and unsolicited messages, except as specifically allowed by these Terms</p>
                <p>8. use the Service in an illegal way or to commit an illegal act in relation to the Service or that otherwise results in fines, penalties, and other liability to TRON or others, or</p>
                <p>9. access the Service from a jurisdiction where it is illegal or unauthorized.</p>
                <h3>XI. TRON’s Liability</h3>
                <p>We are not liable for the actions of users when they use the Service. We may also change the Service at any time and are not liable for how this may affect you. We do not guarantee the quality or accuracy of any content you view using the Service or other websites.</p>
                <p>Changes to the Service. We may change, suspend, or discontinue any aspect of the Service at any time, including hours of operation or availability of the Service or any feature, without notice or liability.</p>
                <p>User Disputes. We are not responsible for any disputes or disagreements between you and any third party you interact with using the Service. You assume all risk associated with dealing with third parties. You agree to resolve disputes directly with the other party. You release TRON of all claims, demands, and damages in disputes among users of the Service. You also agree not to involve us in such disputes. Use caution and common sense when using the Service.</p>
                <p>Content Accuracy. We make no representations about accuracy, reliability, completeness, or timeliness of any contents of the Service. Similarly, we make no representations about accuracy, reliability, completeness, or timeliness of any data from a third-party service provider or the quality or nature of third-party products or services obtained through the Service. Use the Service at your own risk.</p>
                <p>Third-Party Websites and Promotions. The Service may include links to third-party websites and applications, including opportunities to purchase goods and services from, or participate in special contests, sweepstakes, and other promotions (“Promotions”) of our business partners, charities, sponsors or other third parties (“Third-Party Partners”). You are responsible for evaluating whether you want to access or use them. We are not responsible for and do not endorse any features, content, advertising, products, or other materials on other websites or applications. You assume all risk and we disclaim all liability arising from your use of them. We make no promises and disclaim all liability of specific results from the use of the Service.</p>
                <p>By participating in a Promotion, you agree to the rules that govern that Promotion, which may contain specific requirements about how your Personal Information (as defined in TRON’s Privacy Policy) is used, including allowing the sponsor of the Promotion to use your name, voice and/or likeness in advertising or marketing associated with the Promotion.</p>
                <p>Released Parties Defined. “Released Parties” include TRON and its affiliates, officers, directors, employees, agents, partners, and licensors.</p>
                <h3>A. DISCLAIMER OF WARRANTIES</h3>
                <p>You use the Service at your own risk. We make no warranties or guarantees.</p>
                <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT: (A) YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK, AND THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND THE RELEASED PARTIES EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES AS TO PRODUCTS OR SERVICES OFFERED BY BUSINESSES LISTED ON THE SERVICE, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT; (B) THE RELEASED PARTIES MAKE NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY GOODS OR SERVICE AVAILABLE ON THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (v) ANY ERRORS IN THE SERVICE WILL BE CORRECTED; (C) THE SERVICE OR THE SERVER THAT MAKES THE SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; AND (D) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS ACCESSED AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF ANY SUCH MATERIAL. TRON MAKES NO REPRESENTATION OR WARRANTY AS TO THE RELIABILITY, SAFETY, TIMELINESS, QUALITY, SUITABILITY OR AVAILABILITY OF ANY SERVICES OBTAINED FROM THIRD PARTIES THROUGH THE USE OF THE SERVICE. YOU ACKNOWLEDGE AND AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SERVICE AND ANY THIRD-PARTY SERVICES REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
                <h3>B. LIMITATION OF LIABILITY AND INDEMNIFICATION</h3>
                <p>We are not liable for anything that happens to you that somehow may be connected to your use of the Service. If you use the Service in a way that causes us to be included in litigation, you agree to pay all legal fees and costs for Released Parties.</p>
                <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT THE RELEASED PARTIES SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER TANGIBLE OR INTANGIBLE LOSSES (EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE, INCLUDING DELAYS, DELIVERY FAILURES OR OTHER DAMAGE RELATING TO LIMITATIONS, DELAYS AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION, OR SERVICES OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH, FROM, OR AS A RESULT OF THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY USER OR THIRD PARTY ON THE SERVICE; (v) YOUR RELIANCE ON CONTENT MADE AVAILABLE BY US; OR (vi) ANY OTHER MATTER RELATING TO THE SERVICE. TRON AND/OR ITS LICENSORS WILL NOT BE LIABLE FOR ANY LOSS, DAMAGE, OR INJURY WHICH MAY BE INCURRED BY YOU, INCLUDING BUT NOT LIMITED TO LOSS, DAMAGE, OR INJURY ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THE SERVICE, INCLUDING BUT NOT LIMITED ANY LOSS, DAMAGE, OR INJURY RESULTING FROM ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY SERVICE PROVIDER.</p>
                <p>TRON MAY INTRODUCE YOU TO THIRD-PARTY TRANSPORTATION PROVIDERS TO PROVIDE YOU TRANSPORTATION, BUT TRON DOES NOT ASSESS THE SUITABILITY, LEGALITY, OR ABILITY OF ANY THIRD-PARTY TRANSPORTATION PROVIDER AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS, OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE THIRD-PARTY TRANSPORTATION PROVIDER. YOU ACKNOWLEDGE THAT TRON DOES NOT MONITOR ANY THIRD-PARTY TRANSPORTATION PROVIDER’S ON-GOING COMPLIANCE WITH ANY AND ALL LICENSING AND/OR PERMITTING RULES AND REGULATIONS, AND TRON WILL NOT BE RESPONSIBLE FOR ANY LIABILITY, CLAIMS, OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO A THIRD-PARTY TRANSPORTATION PROVIDER’S FAILURE TO MAINTAIN A CURRENT LICENSE AND/OR PERMIT. TRON WILL NOT BE A PARTY TO DISPUTES OR NEGOTIATIONS OF DISPUTES BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING TRON’S SERVICES RESTS SOLELY WITH YOU. TRON WILL NOT ASSESS THE SUITABILITY, LEGALITY, OR ABILITY OF ANY SUCH THIRD PARTIES AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE SERVICE, OR IN ANY WAY RELATED TO THE THIRD PARTIES INTRODUCED TO YOU BY THE SERVICE.</p>
                <p>THE QUALITY OF THE TRANSPORTATION SERVICES SCHEDULED THROUGH THE SERVICE IS ENTIRELY THE RESPONSIBILITY OF THE THIRD-PARTY PROVIDER WHO ULTIMATELY PROVIDES SUCH TRANSPORTATION SERVICES TO YOU. YOU UNDERSTAND THAT BY USING THE SERVICE, YOU MAY BE EXPOSED TO CONTENT THAT IS POTENTIALLY DANGEROUS, OFFENSIVE, HARMFUL TO MINORS, UNSAFE, OR OTHERWISE OBJECTIONABLE AND THAT YOU USE THE SERVICE AT YOUR OWN RISK.</p>
                <p>You agree to defend, indemnify, and hold harmless the Released Parties from and against any claims, actions, or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from (i) your use of or reliance on any Third-Party Content, (ii) your use of or reliance on any TRON Content, (iii) your violation of any rights of any third party, including transportation service providers booked through the Service; or (iv) your breach of these Terms. We shall provide notice to you promptly of any such claim, suit, or proceeding.</p>
                <h3>XII. General Terms</h3>
                <p>These Terms constitute the entire agreement between you and TRON concerning your use of the Service. Our failure to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect. The section titles and annotations in these Terms are for convenience only and have no legal or contractual effect.</p>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        
    }
</script>