<template>
    <div class="term">
        <div class="container">
            <div class="privacy">
                <h2>Syarat dan Ketentuan</h2>
                <h3>I. Pendahuluan dan Kelayakan</h3>
                <p>Harap baca Ketentuan Penggunaan ini ("Ketentuan") dengan cermat sebelum menggunakan Layanan</p>
                <p>Ketentuan ini termasuk Kebijakan Privasi TRON, yang digabungkan dengan referensi ke dalam Ketentuan ini. Kami telah menyertakan beberapa anotasi dalam kotak untuk membantu menjelaskan atau menekankan bagian utama. Anotasi ini hanya untuk kenyamanan dan tidak memiliki efek hukum atau kontrak</p>
                <p>Perjanjian ini adalah kontrak yang mengikat secara hukum. Perjanjian ini dapat berubah seiring perubahan bisnis kami, dan Anda setuju Anda akan memeriksa atas setiap pembaruan secara berkala. Jika Anda terus menggunakan Layanan, maka Anda menerima perubahan apa pun atas Perjanjian ini.</p>
                <p>Perjanjian Mengikat. Ketentuan ini merupakan perjanjian yang mengikat antara Anda dan PT Teknologi Rancang Olah Nusantara dan afiliasinya serta anak perusahaannya ("TRON," "Perusahaan," "kami," "kami"). "Anda" dan "pengguna" berarti semua pengguna Layanan. Anda menerima Ketentuan ini setiap kali Anda mengakses Layanan. Jika Anda tidak menerima Ketentuan ini, Anda tidak dapat menggunakan Layanan. Jika Anda berusia di bawah 18 tahun, Anda menjamin bahwa Anda memiliki izin resmi dari orang tua atau wali Anda untuk mengakses dan menggunakan Layanan.</p>
                <p>Revisi terhadap Ketentuan. Kami dapat merevisi Ketentuan ini kapan saja dengan memposting versi yang diperbarui. Anda harus mengunjungi halaman ini secara berkala untuk meninjau Ketentuan terbaru karena Anda terikat olehnya. Dalam hal Anda tetap menggunakan Layanan setelah perubahan atas Ketentuan ini, hal tersebut merupakan penerimaan Anda yang mengikat terhadap Ketentuan ini.</p>
                <p>Istilah "posting" dan "memposting" seperti yang digunakan dalam Ketentuan ini berarti tindakan mengirimkan, mentransmisikan, berbagi, mengunggah, menerbitkan, menampilkan, atau tindakan serupa pada Layanan</p>
                <h3>II Pelayanan</h3>
                <p>"Layanan" berarti situs web, aplikasi seluler, atau layanan Internet apa pun di bawah kendali TRON, baik sebagian atau lainnya, sehubungan dengan menyediakan platform online TRON yang menghubungkan pengguna dengan penyedia transportasi berbagi kendaraan di kota-kota besar. Setiap pemesanan yang dilakukan pengguna dengan penyedia transportasi berbagi kendaraan tersebut di Layanan adalah "Reservasi," dan setiap perjalanan yang diambil melalui Reservasi adalah "Perjalanan".</p>
                <p>TRON TIDAK MENYEDIAKAN LAYANAN TRANSPORTASI DAN BUKAN ANGKUTAN TRANSPORTASI. HAL INI TERGANTUNG PADA PENYEDIA TRANSPORTASI PIHAK KETIGA, DRIVER, ATAU OPERATOR KENDARAAN UNTUK MENAWARKAN LAYANAN TRANSPORTASI YANG MUNGKIN DIJADWALKAN MELALUI LAYANAN. TRON MENAWARKAN INFORMASI DAN METODE UNTUK MENDAPATKAN LAYANAN TRANSPORTASI PIHAK KETIGA, TETAPI TIDAK DAN TIDAK BERARTI MENYEDIAKAN LAYANAN TRANSPORTASI ATAU BERTINDAK DENGAN CARA APA PUN SEBAGAI ANGKUTAN TRANSPORTASI, DAN TIDAK MEMILIKI TANGGUNG JAWAB ATAS LAYANAN TRANSPORTASI YANG DISEDIAKAN KEPADA ANDA MELALUI PIHAK KETIGA TERSEBUT.</p>
                <p>Dengan menggunakan Layanan untuk melakukan Reservasi untuk Perjalanan, Anda memilih untuk menggunakan layanan transportasi ridesharing. </p>
                <p>Layanan saat ini ditawarkan sebagai uji beta, dan dengan demikian terbatas dalam kapasitas, wilayah geografis, dan jam operasinya. Wilayah geografis dan jam operasi dipilih berdasarkan kapasitas terbatas Layanan selama pengujian beta dan antisipasi kami terhadap permintaan untuk Layanan dan tidak memiliki alasan atau niat diskriminatif. Kami mengantisipasi perluasan Layanan ke area geografis yang lebih luas dan/atau jam operasional tambahan di masa mendatang. Jika Anda memiliki rekomendasi untuk waktu tambahan dan/atau bidang layanan, silakan hubungi kami di support@tron.id.</p>
                <h3>III. Kelayakan untuk Menggunakan Layanan</h3>
                <p>Anak-anak. Tidak ada bagian dari Layanan yang ditujukan untuk orang yang berusia di bawah 13 tahun. JIKA ANDA DI BAWAH 13 TAHUN USIA, TOLONG UNTUK TIDAK MENGGUNAKAN ATAU MENGAKSES LAYANAN</p>
                <p>Tidak seorang pun di bawah usia 18 tahun diizinkan untuk mendaftar atau menggunakan Layanan tanpa persetujuan orang tua atau wali. Jika Anda berusia di bawah 18 tahun, dengan mendaftar dan menggunakan Layanan, Anda menjamin dan menyatakan bahwa Anda memiliki izin untuk menggunakan Layanan dari orang tua atau wali. Jika Anda adalah orang tua atau wali dari anak di bawah umur yang telah mendaftar atau menggunakan Layanan tanpa persetujuan Anda, silakan hubungi kami di support@tron.id</p>
                <p>Agen Perusahaan, Entitas, atau Organisasi. Jika Anda menggunakan Layanan atas nama perusahaan, entitas, atau organisasi (secara kolektif disebut "Organisasi"), maka Anda menyatakan dan menjamin bahwa Anda:<br>
                1. adalah perwakilan resmi dari Organisasi tersebut;<br>
                2. memiliki wewenang untuk mengikat Organisasi tersebut dengan Ketentuan ini; dan<br>
                3. setuju untuk terikat oleh Ketentuan ini atas nama Organisasi itu.
                </p>
                <h3>IV. Akun Anda</h3>
                <p>Anda bertanggung jawab atas kredensial masuk Anda dan untuk menjaga agar informasi Anda diberikan secara akurat.</p>
                <p>Anda bertanggung jawab atas aktivitas apa pun yang dihasilkan dari penggunaan kredensial masuk Anda pada Layanan.</p>
                <p>Anda menyatakan dan menjamin bahwa informasi yang Anda berikan kepada Perusahaan saat menggunakan Layanan dan setiap saat akan benar, akurat, terkini, dan lengkap.</p>
                <p>Kredensial Masuk Anda. Untuk menggunakan Layanan, Anda akan masuk dengan memberikan nama pengguna, kata sandi, dan nomor telepon seluler. Akun Anda bersifat pribadi untuk Anda, dan Anda tidak boleh membagikan informasi akun Anda dengan, atau </p>
                <p>mengizinkan akses ke akun Anda oleh, pihak ketiga mana pun. Oleh karena Anda akan bertanggung jawab atas semua aktivitas yang terjadi di dalam kredensial akses Anda (termasuk, namun tidak terbatas pada, perilaku orang lain yang bepergian dalam grup Anda), Anda setuju untuk menggunakan upaya yang wajar untuk mencegah akses tidak sah ke atau penggunaan Layanan dan untuk menjaga kerahasiaan nama pengguna dan kata sandi Anda, dan perangkat apa pun yang Anda gunakan untuk mengakses Layanan.</p>
                <p>Anda setuju untuk segera memberi tahu kami jika ada pelanggaran kerahasiaan informasi kredensial masuk Anda. Jika Anda memiliki alasan untuk meyakini bahwa informasi akun Anda telah disusupi atau bahwa akun Anda telah diakses oleh pihak ketiga, Anda setuju untuk segera memberi tahu Perusahaan melalui email ke support@tron.id. Anda akan bertanggung jawab penuh atas kerugian yang ditimbulkan oleh Perusahaan dan orang lain atas penggunaan akun Anda secara tidak sah.</p>
                <h3>V. Pembayaran dan Penagihan</h3>
                <p>TRON membebankan biaya ("Biaya") untuk penggunaan Layanan. Anda akan dikenakan biaya ketika Perjalanan Anda selesai, dengan catatan bahwa kami dapat melakukan pra-otorisasi dan menahan perkiraan jumlah Biaya pada kartu Anda sebelum Perjalanan dimulai. Semua Biaya tidak dapat dikembalikan. Biaya tidak termasuk pajak dan biaya tambahan pemerintah lainnya.</p>
                <p>Kebijakan Pembatalan. Jika Anda membatalkan Reservasi, kami mungkin membebankan biaya kepada Anda. Pembatalan yang berulang dapat mengakibatkan penangguhan akun Anda, berdasarkan diskresi dan kebijakan tunggal TRON.</p>
                <p>Kebijakan No-Show. Jika Anda tidak hadir pada waktu dan tempat yang ditentukan dalam Reservasi Anda, kami dapat membebankan biaya kepada Anda. Contoh “tidak muncul” yang berulang kali dapat mengakibatkan penangguhan akun Anda, berdasarkan diskresi dan kebijakan tunggal TRON.</p>
                <p>Biaya Pembersihan/Kerusakan. Jika interior atau eksterior kendaraan pengemudi Anda rusak atau kotor akibat tindakan yang disengaja atau lalai seperti membanting pintu secara agresif, muntah, atau kecelakaan hewan peliharaan, maka anda dapat dikenakan biaya tambahan atas pembersihan atau kerusakan yang dapat dinilai dan dibebankan.</p>
                <p>Kredit TRON dan Kode Promosi. Anda dapat membeli kredit (“Kredit TRON”) untuk perjalanan yang akan datang. Pembelian Kredit TRON tidak dapat dikembalikan dan hanya dapat digunakan dengan Layanan. TRON dapat menawarkan kode promosi dengan berbagai fitur dan tarif yang dapat ditukarkan dengan Kredit TRON. Kode promosi semacam itu valid hingga tanggal kedaluwarsa yang dinyatakan.</p>
                <h3>VI. Tamu tambahan</h3>
                <p>Jika Anda membuat Reservasi dan banyak orang bepergian dalam grup Anda, Anda, sebagai akun yang terkait dengan Reservasi, bertanggung jawab atas perilaku semua orang yang bepergian dalam grup Anda.</p>
                <p>Ketika Anda melakukan Reservasi, Anda harus menunjukkan berapa banyak orang yang bepergian di pesta Anda. Jika tidak, kami berhak menolak layanan untuk tamu tambahan atau membebankan biaya tambahan.</p>
                <h3>VII. Komunikasi</h3>
                <p>TRON dapat berkomunikasi dengan Anda melalui email, pesan teks atau memposting pemberitahuan di Layanan. Anda dapat meminta kami memberikan pemberitahuan tentang pelanggaran keamanan secara tertulis.</p>
                <p>Anda setuju untuk menerima email dari kami di alamat email yang Anda berikan kepada kami untuk tujuan terkait layanan pelanggan.</p>
                <p>Pemberitahuan Elektronik. Dengan menggunakan Layanan atau memberikan Informasi Pribadi kepada kami, Anda setuju bahwa kami dapat berkomunikasi dengan Anda secara elektronik mengenai masalah keamanan, privasi, dan administrasi yang berkaitan dengan penggunaan Layanan oleh Anda. Jika kami mengetahui tentang pelanggaran sistem keamanan, kami dapat mencoba memberi tahu Anda secara elektronik dengan memposting pemberitahuan pada Layanan atau mengirim email kepada Anda. Anda akan memiliki hak hukum untuk menerima pemberitahuan ini secara tertulis. Untuk menerima pemberitahuan tertulis tentang pelanggaran keamanan (atau untuk menarik persetujuan Anda dari menerima pemberitahuan elektronik), silakan menulis kepada kami di support@tron.id.</p>
                <p>Pesan Teks SMS. Kami dapat mengirimi Anda pesan teks SMS ke nomor telepon yang Anda berikan pada saat pendaftaran (i) ketika Anda mendaftar ke Layanan, (ii) saat Anda melakukan Reservasi, (iii) saat kendaraan Anda mendekati pengambilan yang ditunjuk. lokasi naik, (iv) saat kendaraan Anda berada di lokasi penjemputan yang ditentukan, dan (v) saat Anda mereset kata sandi dengan Layanan. Pesan teks dan kecepatan data, sebagaimana ditentukan oleh operator nirkabel Anda, mungkin berlaku. Dengan mendaftar ke Layanan, Anda menyetujui untuk menerima pesan teks SMS ini.</p>
                <h3>VIII. Kepemilikan dan Penggunaan Konten TRON</h3>
                <p>TRON memiliki hak atas semua konten yang kami sediakan melalui Layanan, tetapi Anda dapat menggunakannya saat Anda menggunakan Layanan. Anda tidak dapat menggunakan logo kami tanpa izin tertulis dari kami.</p>
                <p>Istilah "konten" atau "konten" seperti yang digunakan secara umum dalam Ketentuan ini berarti teks, grafik, gambar, musik, perangkat lunak (tidak termasuk Layanan), audio, video, informasi atau materi lainnya.</p>
                <p>Isi Layanan mencakup: desain, teks, grafik, gambar, video, informasi, logo, ikon tombol, perangkat lunak, file audio, kode komputer, dan konten TRON lainnya (secara bersama-sama disebut, "Konten TRON"). Semua Konten TRON dan kompilasi (berarti pengumpulan, pengaturan, dan perakitan) dari semua Konten TRON adalah milik TRON atau pemberi lisensinya dan dilindungi oleh hak cipta, merek dagang, dan undang-undang lainnya.</p>
                <p>Lisensi untuk Anda. Kami mengizinkan Anda, tunduk pada Ketentuan ini, untuk mengakses dan menggunakan Layanan dan Konten TRON semata-mata untuk melakukan Reservasi. Penggunaan lain secara tegas dilarang. Lisensi ini dapat dibatalkan kapan saja tanpa pemberitahuan dan dengan atau tanpa alasan. Penggunaan Konten TRON secara tidak sah dapat melanggar hak cipta, merek dagang, dan peraturan dan undang-undang komunikasi yang berlaku dan sangat dilarang. Anda harus menjaga seluruh hak cipta, merek dagang, merek layanan, dan pemberitahuan hak milik lainnya yang terkandung dalam Konten TRON asli pada setiap salinan yang Anda buat dari Konten TRON.</p>
                <p>Tanda TRON. TRON, logo TRON, dan logo TRON lainnya serta nama produk dan layanan adalah atau mungkin merupakan merek dagang dari TRON ("Merek TRON"). Tanpa izin tertulis kami sebelumnya, dan kecuali hanya diaktifkan oleh tautan apa pun yang disediakan oleh kami, Anda setuju untuk tidak menampilkan atau menggunakan dengan cara apa pun Merek TRON.</p>
                <h3>IX. Hak Kekayaan Intelektual dan Lisensi Anda untuk Menggunakan</h3>
                <p>Anda (atau orang-orang yang memungkinkan Anda untuk menggunakan konten mereka), memiliki semua konten yang Anda posting dalam menggunakan Layanan. Namun, kami dapat menggunakannya untuk tujuan apa pun, termasuk dalam materi pemasaran kami. Kami juga dapat memodifikasi konten Anda agar berfungsi lebih baik.</p>
                <p>Sangat penting bahwa Anda memiliki izin untuk menggunakan konten orang lain, atau mereka (atau orang tua atau wali mereka) dapat menuntut Anda karena melanggar hak hukum mereka.</p>
                <p>a. TRON Tidak Klaim atas Kepemilikan. Layanan dapat memberi Pengguna kemampuan untuk memposting konten ("Konten Pengguna"). TRON mengklaim tidak memiliki atau mengendalikan Konten Pengguna. Anda atau pemberi lisensi pihak ketiga, yang sesuai, mempertahankan semua hak cipta, paten, dan hak merek dagang untuk setiap konten yang Anda posting di atau melalui Layanan. Anda bertanggung jawab untuk melindungi hak-hak tersebut.</p>
                <p>b. Penggunaan TRON atas Konten yang Diposting dalam Layanan. Dengan memposting Konten Pengguna pada atau melalui Layanan, dan tunduk pada Kebijakan Privasi TRON, Anda memberikan TRON hak global, non-eksklusif, tidak dapat dibatalkan, abadi, bebas royalti, dapat ditransfer ke lisensi, sublisensi, penggunaan, tampilan, salin, adaptasi, menjual, mentransfer, memodifikasi, menghapus, menerbitkan, mentransmisikan, menyiarkan,  melakukan, atau menampilkan secara publik Konten Pengguna Anda untuk tujuan apa pun tanpa kompensasi kepada Anda, termasuk untuk tujuan mempromosikan TRON dan layanannya. Meskipun kami akan berusaha sebaik mungkin untuk tidak menggunakan Konten Pengguna Anda dengan cara yang mungkin tidak menyenangkan bagi Anda, Anda melepaskan hak apa pun yang mungkin Anda miliki tentang Konten Pengguna Anda yang diubah atau dimanipulasi dengan cara apa pun yang mungkin tidak menyenangkan bagi Anda. Silakan kirim email kepada kami di support@tron.id jika Anda yakin Konten Pengguna Anda digunakan dengan cara yang tidak menyenangkan dan kami akan melakukan apa yang dapat kami lakukan secara wajar untuk memperbaiki penggunaan Konten Pengguna Anda tersebut. Lisensi yang diberikan dalam paragraf ini akan terus berlanjut bahkan setelah Anda berhenti menggunakan Layanan. TRON berhak menolak untuk menerima, memposting, menampilkan, atau mentransmisikan Konten Pengguna apa pun atas kebijakannya sendiri.</p>
                <p>c. Anda Tidak Memperoleh Kepemilikan dalam Konten TRON atau Lainnya. Anda memahami dan menyetujui bahwa Anda tidak akan memperoleh hasil dari penggunaan Layanan oleh Anda, hak, kepemilikan, atau minat pada atau atas konten yang dikirimkan melalui Layanan atau dalam hak kekayaan intelektual apa pun (termasuk, namun tidak terbatas pada, hak cipta, paten apa pun, merek dagang, rahasia dagang atau hak lainnya) dalam konten. TRON sendiri (dan pemberi lisensinya, jika berlaku) memiliki semua hak, kepemilikan, dan kepentingan, termasuk semua hak kekayaan intelektual terkait, di dalam dan pada Layanan. Nama Perusahaan, logo Perusahaan, dan nama produk yang terkait dengan Layanan adalah merek dagang dari TRON atau pihak ketiga, dan tidak ada hak atau lisensi yang diberikan untuk menggunakannya.</p>
                <p>d. Anda Harus Memiliki Hak atas Konten yang Anda Posting. Anda menyatakan dan menjamin bahwa: (i) Anda memiliki konten yang diposting oleh Anda pada atau melalui Layanan atau memiliki hak untuk memberikan lisensi yang ditetapkan dalam Ketentuan ini, (ii) posting dan penggunaan Konten Pengguna Anda pada atau melalui Layanan tidak melanggar hak privasi, hak publisitas, hak cipta, hak kontrak, hak kekayaan intelektual, atau hak lain apa pun dari orang atau entitas mana pun, dan (iii) postingan Konten Pengguna pada Layanan tidak mengakibatkan pelanggaran terhadap kontrak antara Anda dan pihak ketiga. Anda setuju untuk membayar semua royalti, biaya, dan uang lain yang terutang kepada siapa pun dengan alasan konten yang Anda poskan pada atau melalui Layanan. Anda juga mengakui dan menyetujui bahwa Konten Pengguna Anda adalah non-rahasia dan non-kepemilikan.</p>
                <p>e. Lisensi Tambahan. Materi tertentu yang tersedia untuk diunduh dari atau melalui Layanan dapat dikenakan syarat dan ketentuan lisensi tambahan atau berbeda. Layanan berisi konten dari Pengguna dan pemberi lisensi TRON lainnya. Kecuali sebagaimana ditentukan dalam Ketentuan ini, Anda tidak boleh menyalin, memodifikasi, menerjemahkan, menerbitkan, menyiarkan, mentransmisikan, mendistribusikan, melakukan, menampilkan, atau menjual konten apa pun yang muncul di atau melalui Layanan.</p>
                <h3>X. Penafian, Pembatasan, dan Larangan Konten Pihak Ketiga</h3>
                <p>Anda bertanggung jawab atas tindakan Anda saat menggunakan dan mengandalkan Layanan atau konten yang tersedia di Layanan.</p>
                <p>Kami tidak mewakili atau menjamin kebenaran, akurasi, atau keandalan konten, yang diposting oleh pihak ketiga ("Konten Pihak Ketiga"). Anda menerima bahwa ketergantungan pada materi yang diposting oleh pengguna lain atau penyedia layanan pihak ketiga akan menjadi risiko Anda sendiri. Dengan menggunakan Layanan, Anda menerima risiko bahwa Anda mungkin terpapar ke konten yang tidak pantas. TRON tidak mendukung apa pun, juga tidak bertanggung jawab atas, Konten Pihak Ketiga pada Layanan.</p>
                <p>Jangan melakukan hal-hal buruk dengan Layanan, mencoba memecahkannya, atau mencuri kerja keras kami.</p>
                <p>Anda setuju untuk menggunakan Layanan hanya untuk tujuan yang dimaksud. Anda harus menggunakan Layanan untuk mematuhi semua privasi, perlindungan data, kekayaan intelektual, dan undang-undang lain yang berlaku. Penggunaan Layanan berikut ini dilarang. Anda mungkin tidak:</p>
                <p>1. upaya untuk mengganggu, membahayakan, merekayasa balik, mencuri dari, atau mendapatkan akses tidak sah ke Layanan, akun pengguna, atau teknologi dan peralatan yang mendukung Layanan;</p>
                <p>2. bingkai, cermin, atau tautan ke Layanan tanpa izin;</p>
                <p>3. menggunakan penambangan data, robot, laba-laba web, virus atau worm atau perangkat pengumpulan data lainnya pada atau melalui Layanan, termasuk program apa pun yang dapat membuat beberapa permintaan server per detik, atau terlalu membebani atau menghambat operasi atau kinerja Layanan;</p>
                <p>4. memposting informasi yang tidak lengkap, salah, atau menyesatkan, menyamar sebagai orang lain, atau salah menggambarkan afiliasi Anda dengan seseorang atau entitas;</p>
                <p>5. mengungkapkan informasi pribadi tentang orang lain, atau memposting, mengirim atau menyimpan materi yang melanggar, cabul, mengancam, memfitnah atau menyiksa, termasuk materi yang berbahaya bagi anak-anak, melanggar hak-hak pihak ketiga, atau dimaksudkan untuk melecehkan, menyalahgunakan, atau menurunkan orang lain;</p>
                <p>6. menjual, mentransfer, atau mengalihkan hak Anda untuk menggunakan Layanan kepada pihak ketiga tanpa persetujuan tertulis dari kami;</p>
                <p>7. memposting iklan atau tautan atau konten pemasaran, termasuk spam atau pesan duplikat dan tidak diminta, kecuali sebagaimana diizinkan secara khusus oleh Ketentuan ini;</p>
                <p>8. menggunakan Layanan dengan cara ilegal atau melakukan tindakan ilegal dalam kaitannya dengan Layanan atau yang menghasilkan denda, penalti, dan tanggung jawab lain kepada TRON atau orang lain; atau</p>
                <p>9. mengakses Layanan dari yurisdiksi di mana itu ilegal atau tidak sah. </p>
                <h3>XI. Tanggung Jawab TRON</h3>
                <p>Kami tidak bertanggung jawab atas tindakan pengguna saat mereka menggunakan Layanan. Kami juga dapat mengubah Layanan kapan saja dan tidak bertanggung jawab atas bagaimana hal ini dapat memengaruhi Anda. Kami tidak menjamin kualitas atau keakuratan konten apa pun yang Anda lihat menggunakan Layanan atau situs web lain.</p>
                <p>Perubahan pada Layanan. Kami dapat mengubah, menangguhkan, atau menghentikan aspek apa pun dari Layanan kapan saja, termasuk jam operasi atau ketersediaan Layanan atau fitur apa pun, tanpa pemberitahuan atau pertanggungjawaban.</p>
                <p>Perselisihan Pengguna. Kami tidak bertanggung jawab atas perselisihan atau ketidaksepakatan antara Anda dan pihak ketiga mana pun yang berinteraksi dengan Anda menggunakan Layanan. Anda menganggap semua risiko yang terkait dengan berurusan dengan pihak ketiga. Anda setuju untuk menyelesaikan perselisihan secara langsung dengan pihak lain. Anda melepaskan TRON dari semua klaim, tuntutan, dan kerusakan dalam perselisihan di antara pengguna Layanan. Anda juga setuju untuk tidak melibatkan kami dalam perselisihan semacam itu. Berhati-hatilah dan gunakan akal sehat pada saat menggunakan Layanan.</p>
                <p>Akurasi Konten. Kami tidak membuat pernyataan tentang keakuratan, keandalan, kelengkapan, atau ketepatan waktu dari setiap konten Layanan. Demikian pula, kami tidak membuat pernyataan tentang keakuratan, keandalan, kelengkapan, atau ketepatan waktu dari data dari penyedia layanan pihak ketiga atau kualitas atau sifat produk atau layanan pihak ketiga yang diperoleh melalui Layanan. Gunakan Layanan dengan risiko Anda sendiri.</p>
                <p>Situs Web dan Promosi Pihak Ketiga. Layanan dapat mencakup tautan ke situs web dan aplikasi pihak ketiga, termasuk peluang untuk membeli barang dan layanan dari, atau berpartisipasi dalam kontes khusus, undian, dan promosi lainnya ("Promosi") dari mitra bisnis, amal, sponsor, atau pihak ketiga lainnya ("Mitra Pihak Ketiga"). Anda bertanggung jawab untuk mengevaluasi apakah Anda ingin mengakses atau menggunakannya. Kami tidak bertanggung jawab atas dan tidak mendukung fitur, konten, iklan, produk, atau materi lainnya di situs web atau aplikasi lain. Anda menanggung semua risiko dan kami melepaskan semua tanggung jawab yang timbul dari penggunaan Anda terhadap mereka. Kami tidak membuat janji dan menafikan semua tanggung jawab atas hasil spesifik dari penggunaan Layanan.</p>
                <p>Dengan berpartisipasi dalam Promosi, Anda menyetujui aturan yang mengatur Promosi itu, yang mungkin berisi persyaratan spesifik tentang bagaimana Informasi Pribadi Anda (sebagaimana didefinisikan dalam Kebijakan Privasi TRON) digunakan, termasuk mengizinkan sponsor Promosi untuk menggunakan nama Anda, suara dan / atau kemiripan dalam iklan atau pemasaran yang terkait dengan Promosi.</p>
                <p>Pihak Dirilis Ditentukan. “Pihak yang Dirilis” termasuk TRON dan afiliasinya, pejabat, direktur, karyawan, agen, mitra, dan pemberi lisensi.</p>
                <h3>A. PENAFIAN JAMINAN</h3>
                <p>Anda menggunakan Layanan dengan risiko Anda sendiri. Kami tidak membuat pernyataan atau jaminan.</p>
                <p>ANDA SECARA TEGAS MEMAHAMI DAN MENYETUJUI BAHWA: (A) PENGGUNAAN LAYANAN INI DI RISIKO ANDA SENDIRI, DAN LAYANAN INI DISEDIAKAN DENGAN DASAR "SEBAGAIMANA ADANYA" DAN "SEBAGAIMANA TERSEDIA" DAN PIHAK YANG DIPERLUASKAN SECARA TEGAS MENYATAKAN SEMUA JAMINAN APA PUN, BAIK TERSURAT MAUPUN TERSIRAT, TERMASUK, TETAPI TIDAK TERBATAS PADA, JAMINAN SEBAGAI PRODUK ATAU LAYANAN YANG DITAWARKAN OLEH BISNIS YANG TERDAFTAR PADA LAYANAN, JAMINAN TERMASUK DAGANG KEMAMPUAN, KESESUAIAN UNTUK TUJUAN TERTENTU, DAN KECUALI UNTUK NASIB; (B) PIHAK YANG DIRELEPASI TIDAK MEMBUAT JAMINAN (i) LAYANAN AKAN MEMENUHI PERSYARATAN ANDA, (ii) LAYANAN TIDAK AKAN TERGANGGU, TEPAT WAKTU, AMAN, ATAU BEBAS DARI KESALAHAN, (iii) HASIL YANG DAPAT DIPEROLEH DARI PENGGUNAAN LAYANAN AKAN TEPAT ATAU DAPAT DIANDALKAN, (iv) KUALITAS BARANG ATAU LAYANAN YANG TERSEDIA DALAM LAYANAN AKAN MEMENUHI HARAPAN ANDA, DAN (v) KESALAHAN DALAM LAYANAN AKAN DIPERBAIKI; (C) LAYANAN ATAU SERVER YANG MEMBUAT LAYANAN YANG TERSEDIA ADALAH BEBAS VIRUS ATAU KOMPONEN BERBAHAYA LAINNYA; DAN (D) SETIAP MATERI YANG DIUNDUH ATAU DENGAN KATA LAIN YANG DIPEROLEH MELALUI PENGGUNAAN LAYANAN INI DIAKSES DALAM KEBIJAKAN DAN RISIKO SENDIRI, DAN ANDA AKAN BERTANGGUNG JAWAB ATAS KERUSAKAN ATAS SISTEM KOMPUTER ATAU PERANGKAT MOBIL ATAU KURANGNYA DARI DATA. ATAU PENGGUNAAN MATERI TERSEBUT. TRON TIDAK MEMBUAT PERNYATAAN ATAU JAMINAN TERHADAP KEANDALAN, KEAMANAN, KETEPATAN WAKTU, KUALITAS, KESESUAIAN, ATAU KETERSEDIAAN LAYANAN YANG DIPEROLEH DARI PIHAK KETIGA MELALUI PENGGUNAAN LAYANAN. ANDA MENGAKUI DAN MENYETUJUI BAHWA RISIKO SELURUH SELURUHNYA DARI PENGGUNAAN LAYANAN INI DAN LAYANAN PIHAK KETIGA TETAP BERLAKU DENGAN ANDA, SAMPAI PERIODE MAKSIMUM YANG DIIZINKAN OLEH UNDANG-UNDANG.</p>
                <h3>B. BATASAN TANGGUNG JAWAB DAN INDEMNIFIKASI</h3>
                <p>Kami tidak bertanggung jawab atas apa pun yang terjadi pada Anda yang berkaitan dengan penggunaan Layanan oleh Anda. Jika Anda menggunakan Layanan dengan cara yang menyebabkan kami digugat, Anda setuju untuk membayar semua biaya dan biaya hukum untuk Pihak yang Dibebaskan.</p>
                <p>ANDA SECARA TEGAS MEMAHAMI DAN MENYETUJUI BAHWA PIHAK YANG DIBEBASKAN TIDAK BERTANGGUNG JAWAB TERHADAP ANDA ATAS SETIAP KERUSAKAN BAIK SECARA LANGSUNG, TIDAK LANGSUNG, INSIDENTIL, KHUSUS, KONEKUENSIAL ATAU LUAR BIASA, TERMASUK, NAMUN TIDAK TERBATAS PADA, KERUSAKAN ATAS KERUGIAN DARI KEUNTUNGAN, NAMA BAIK, PENGGUNGAAN, DATA ATAU KERUGIAN YANG TIMBUL BAIK NYATA MAUPUN TIDAK NYATA (WALAUPUN TRON TELAH DIBERITAHU ATAS KEMUNGKINAN KERUSAKAN TERSEBUT), YANG TIMBUL DARI: (i) PENGGUNAAN ATAU KETIDAKMAMPUAN UNTUK MENGGUNAKAN LAYANAN, TERMASUK HAMBATAN, KEGAGALAN PENGANTARAN ATAU KERUSAKAN LAINNYA SEHUBUNGAN DENGAN LIMITASI, HAMBATAN DAN MASALAH LAIN DALAM PENGGUNAAN INTERNET DAN KOMUNIKASI SECARA ELEKTRONIK; (ii) BIAYA PENGADAAN ATAS BARANG DAN JASA YANG TIMBUL DARI SETIAP BARANG, DATA, INFORMASI, ATAU LAYANAN YANG DITERIMA ATAU PESANYANG DITERIMA ATAU TRANSAKSI YANG ADA MELALUI, DARI, ATAU SEBAGAI AKIBAT DARI LAYANAN; (iii) AKSES TIDAK SAH ATAS ATAU PERUBAHAN ATAS TRANSMISI ATAU DATA ANDA; (iv) PERNYATAAN ATAU PERILAKU SETIAP PENGGUNA ATAU PIHAK KETIGA LAINNYA ATAS LAYANAN; (v) KEPERCAYAAN ANDA PADA KONTEN YANG DISEDIAKAN OLEH KAMI; ATAU (vi) SETIAP HAL LAINNYA SEHUBUNGAN DENGAN LAYANAN. TRON DAN/ATAU PEMBERI LISENSINYA TIDAK AKAN BERTANGGUNG JAWAB ATAS SETIAP KERUGIAN ATAU KERUSAKAN YANG TIMBUL KARENA ANDA, TERMASUK NAMUN TIDAK TERBATAS PADA, KERUGIAN, KERUSAKAN ATAU CIDERA YANG TIMBUL DARI, ATAU SEHUBUNGAN DENGAN LAYANAN, TERMASUK NAMUN TIDAK TERBATAS PADA SETIAP KERUGIAN ATAU KERUSAKAN AKIBAT RELASI ATAU TRANSAKSI ANTARA ANDA DAN SETIAP PENYEDIA LAYANAN PIHAK KETIGA.</p>
                <p>TRON DAPAT MEMPERKENALKAN ANDA KEPADA PENYEDIA TRANSPORTASI PIHAK KETIGA UNTUK MENYEDIAKAN TRANSPORTASI ANDA, TETAPI TRON TIDAK MENILAI KELAYAKAN, LEGALITAS, ATAU KEMAMPUAN PENYEDIA TRANSPORTASI PIHAK KETIGA DAN ANDA SECARA TEGAS MENGESAMPINGKAN DAN MEMBEBASKAN TRON ATAS SETIAP DAN SELURUH TANGGUNG JAWAB, KLAIM ATAU KERUSAKAN YANG TIMBUL DARI ATAU DALAM BENTUK APAPUN SEHUBUNGAN DENGAN PENYEDIA TRANSPORTASI PIHAK KETIGA. ANDA MENGAKUI BAHWA TRON TIDAK MEMANTAU KEPATUHAN PENYEDIA TRANSPORTASI PIHAK KETIGA DENGAN DAN SELURUH LICENSI DAN/ATAU IZIN YANG DIWAJIBKAN OLEH PERATURAN PERUNDANG-UNDANGAN YANG BERLAKU, DAN TRON TIDAK BERTANGGUNG JAWAB ATAS SETIAP TANGGUNG JAWAB, KLAIM ATAU KERUSAKAN YANG TIMBUL SEHUBUNGAN DENGAN KELALAIAN PENYEDIA TRANSPORTASI PIHAK KETIGA UNTUK MENJAGA IZIN DAN/ATAU LISENSI. TRON TIDAK AKAN MENJADI PIHAK ATAS TUNTUTAN ATAU NEGOSIASI TUNTUTAN ANTARA ANDA DAN PENYEDIA LAYANAN PIHAK KETIGA. TANGGUNG JAWAB ATAS KEPUTUSAN YANG ANDA PUTUSKAN SEHUBUNGAN DENGAN LAYANAN TRON ADALAH KEPUTUSAN TUNGGAL ANDA. TRON TIDAK AKAN MENILAI KELAYAKAN, LEGALITAS ATAU KEMAMPUAN PIHAK KETIGA DAN ANDA SECARA TEGAS MELEPASKAN DAN MEMBEBASKAN TRON DARI SETIAP DAN SELURUH TANGGUNG JAWAB, KLAIM, TUNTUTAN ATAUPUN KERUSAKAN YANG TIMBUL SEHUBUNGAN DENGAN PENGGUNAAN ANDA ATAS LAYANAN, ATAU DALAM HAL APAPUN BERHUBUNGAN DENGAN PIHAK KETIGA YANG DIKENALKAN KEPADA ANDA MELALUI LAYANAN.</p>
                <p>KUALITAS LAYANAN TRANSPORTASI YANG DIJADWALKAN MELALUI LAYANAN INI SEPENUHNYA TANGGUNG JAWAB DARI PENYEDIA PIHAK KETIGA YANG MEMBERIKAN LAYANAN TRANSPORTASI TERSEBUT UNTUK ANDA. ANDA MEMAHAMI BAHWA DENGAN MENGGUNAKAN LAYANAN, ANDA DAPAT TERPAPAR PADA KONTEN YANG BERSIFAT BERBAHAYA, MENYERANG, MERUGIKAN MINORITAS, TIDAK AMAN ATAU SEBALIKNYA DAPAT DIGUGAT DAN ANDA MENGGUNAKAN LAYANAN ATAS RISIKO ANDA SENDIRI.</p>
                <p>Anda setuju untuk membela, mengganti rugi, dan membebaskan Pihak-pihak yang Dilepaskan dari dan terhadap klaim, tindakan, atau tuntutan apa pun, termasuk tanpa batasan biaya hukum dan akuntansi yang masuk akal, menuduh atau menghasilkan dari (i) penggunaan atau kepercayaan Anda pada Pihak Ketiga mana pun. Konten, (ii) penggunaan atau ketergantungan Anda pada Konten TRON, (iii) pelanggaran Anda terhadap hak pihak ketiga, termasuk penyedia layanan transportasi yang dipesan melalui Layanan; atau (iv) pelanggaran Anda terhadap Ketentuan ini. Kami akan segera memberikan pemberitahuan kepada Anda tentang klaim, tuntutan, atau proses tersebut.</p>
                <h3>XII. Ketentuan Umum</h3>
                <p>Ketentuan ini merupakan keseluruhan perjanjian antara Anda dan TRON tentang penggunaan Layanan oleh Anda. Kegagalan kami untuk menjalankan atau menegakkan hak atau ketentuan dari Ketentuan ini tidak akan merupakan pengabaian atas hak atau ketentuan tersebut. Jika ada ketentuan dalam Ketentuan ini yang ditemukan oleh pengadilan dengan yurisdiksi yang kompeten tidak valid, para pihak tetap sepakat bahwa pengadilan harus berusaha untuk memberi efek pada niat para pihak sebagaimana tercermin dalam ketentuan tersebut, dan ketentuan lain dari Ketentuan ini tetap ada kekuatan dan efek penuh. Judul bagian dan anotasi dalam Ketentuan ini hanya untuk kenyamanan dan tidak memiliki pengaruh hukum atau kontrak.</p>
            </div>
        </div> 
    </div>
</template>

<script>
    export default {
        name: 'term',
    }
</script>
